// src/lib/data.ts
export interface ToolData {
  name: string;
  type: 'AI Model' | 'Development Tool';
  category: string;
  description: string;
  features: Record<string, boolean | string>;
  pricing?: string;
  contextWindow?: string;
  benchmark?: string;
}

export const toolData: Record<string, ToolData> = {
  // AI MODELS SECTION
  'claude-sonnet-4': {
    name: 'Claude 4 Sonnet',
    type: 'AI Model',
    category: 'General Purpose AI',
    description: 'Smart, efficient model for everyday coding tasks',
    pricing: '$3/$15 per 1M tokens',
    contextWindow: '200K tokens',
    benchmark: '72.7% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Semantic/deep search': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': 'Limited',
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false
    }
  },
  'claude-opus-4': {
    name: 'Claude 4 Opus',
    type: 'AI Model',
    category: 'Premium AI',
    description: 'Most capable model for complex development tasks',
    pricing: '$15/$75 per 1M tokens',
    contextWindow: '200K tokens',
    benchmark: '72.5% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Semantic/deep search': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': 'Limited',
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false
    }
  },
  'gpt-41': {
    name: 'GPT-4.1',
    type: 'AI Model',
    category: 'General Purpose AI',
    description: 'Advanced language model with large context window',
    pricing: '$2/$8 per 1M tokens',
    contextWindow: '1M tokens',
    benchmark: '54.6% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Semantic/deep search': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true
    }
  },
  'gemini-25-pro': {
    name: 'Gemini 2.5 Pro',
    type: 'AI Model',
    category: 'Multimodal AI',
    description: 'Multimodal AI with voice and visual capabilities',
    pricing: '$1.25/$10 per 1M tokens',
    contextWindow: '1M-2M tokens',
    benchmark: '63.8% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Semantic/deep search': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': 'Limited',
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': true,
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': 'Limited'
    }
  },
  'kimi-k2': {
    name: 'Kimi K2',
    type: 'AI Model',
    category: 'Agentic AI',
    description: 'Open agentic intelligence with massive parameter count',
    pricing: '$0.15/$2.50 per 1M tokens',
    contextWindow: '128K tokens',
    benchmark: '65.8% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Semantic/deep search': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': 'Limited',
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': 'Limited',
      'Voice/audio input': 'Limited',
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': 'Partial',
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false
    }
  },
  'grok-4': {
    name: 'Grok 4',
    type: 'AI Model',
    category: 'Specialized Coding AI',
    description: 'First-principles reasoning with coding specialization',
    pricing: '$300/year',
    contextWindow: '256K tokens',
    benchmark: '75% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Semantic/deep search': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false
    }
  },
  'qwen-3-coder': {
    name: 'Qwen 3 Coder',
    type: 'AI Model',
    category: 'Open Source AI',
    description: 'Agentic coding model with repository-scale understanding',
    pricing: '$0.07-1.10 per 1M tokens',
    contextWindow: '256K-1M tokens',
    benchmark: '68.3% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Semantic/deep search': 'Limited',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': 'Limited',
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': 'Limited',
      'Free tier available': true,
      'Open source': true,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true
    }
  },
  'deepseek-coder': {
    name: 'DeepSeek Coder',
    type: 'AI Model',
    category: 'Open Source AI',
    description: 'High-performance open-source coding model',
    pricing: '$0.07-1.10 per 1M tokens',
    contextWindow: '128K tokens',
    benchmark: '67.1% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': 'Limited',
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Semantic/deep search': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': 'Limited',
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': 'Limited',
      'Free tier available': true,
      'Open source': true,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true
    }
  },

  // DEVELOPMENT TOOLS SECTION
  'github-copilot': {
    name: 'GitHub Copilot',
    type: 'Development Tool',
    category: 'IDE Integration',
    description: 'AI pair programmer with ecosystem integration',
    pricing: 'Free-$39/user/month',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': 'Limited',
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': false,
      'Autonomous agent mode': 'Limited',
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': true,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Semantic/deep search': true,
      'Terminal integration': 'Limited',
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': 'Limited',
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true
    }
  },
  'cursor-ide': {
    name: 'Cursor IDE',
    type: 'Development Tool',
    category: 'AI-Native IDE',
    description: 'AI-first code editor with autonomous capabilities',
    pricing: 'Free-$200/month',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': false,
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': false,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': false,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': 'Privacy mode',
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false
    }
  },
  'windsurf': {
    name: 'Windsurf',
    type: 'Development Tool',
    category: 'AI-Native IDE',
    description: 'AI-powered editing with Cascade agent',
    pricing: 'Free-$60/user/month',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': false,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': false,
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': true,
      'Collaborative editing': true,
      'Custom component libraries': false,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': false,
      'PWA features': false,
      'Offline capabilities': false,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false
    }
  },
  'vercel-v0': {
    name: 'Vercel v0',
    type: 'Development Tool',
    category: 'UI Generator',
    description: 'React/Next.js UI generation from text',
    pricing: '$5-$30/month',
    features: {
      'Real-time code completion': false,
      'Multi-file editing': false,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': false,
      'Angular support': false,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': false,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': false,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': false,
      'Autonomous agent mode': false,
      'Git integration': false,
      'Live preview/hot reload': true,
      'Collaborative editing': false,
      'Custom component libraries': true,
      'API integration assistance': false,
      'Testing code generation': false,
      'Documentation generation': false,
      'Semantic/deep search': false,
      'Terminal integration': false,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': false,
      'PWA features': false,
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': false,
      'Custom model training': false
    }
  },
  'bolt-new': {
    name: 'Bolt.new',
    type: 'Development Tool',
    category: 'Full-Stack Builder',
    description: 'Full-stack web applications with WebContainers',
    pricing: 'Beta',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': false,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': false,
      'Performance optimization suggestions': false,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': false,
      'Autonomous agent mode': 'Limited',
      'Git integration': true,
      'Live preview/hot reload': true,
      'Collaborative editing': false,
      'Custom component libraries': false,
      'API integration assistance': true,
      'Testing code generation': false,
      'Documentation generation': false,
      'Semantic/deep search': false,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': false,
      'PWA features': false,
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': 'Partial',
      'Self-hosting option': true,
      'Enterprise features': false,
      'Privacy mode': false,
      'Custom model training': false
    }
  },
  'jetbrains-ai': {
    name: 'JetBrains AI',
    type: 'Development Tool',
    category: 'IDE Integration',
    description: 'AI assistant integrated into JetBrains IDEs',
    pricing: 'Free-Custom',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': false,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': false,
      'Autonomous agent mode': 'Limited',
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': false,
      'Custom component libraries': false,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': false,
      'PWA features': false,
      'Offline capabilities': true,
      'Voice/audio input': false,
      'Image/design upload': false,
      'Screenshot-to-code': false,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false
    }
  },
  'lovable-ai': {
    name: 'Lovable AI',
    type: 'Development Tool',
    category: 'Full-Stack Builder',
    description: 'AI-powered full-stack app development',
    pricing: 'Free-$30/month',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': false,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': 'Limited',
      'Performance optimization suggestions': 'Limited',
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': 'Limited',
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': true,
      'Collaborative editing': true,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': false,
      'Documentation generation': true,
      'Semantic/deep search': false,
      'Terminal integration': false,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': 'Limited',
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': 'Limited',
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false
    }
  },
  'gemini-cli': {
    name: 'Gemini CLI',
    type: 'Development Tool',
    category: 'Command Line AI',
    description: 'Open-source AI agent for terminal workflows',
    pricing: 'Free',
    features: {
      'Real-time code completion': 'Limited',
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': false,
      'Custom component libraries': 'Limited',
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Semantic/deep search': 'Limited',
      'Terminal integration': 'Limited',
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': false,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': true,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false
    }
  },
  'claude-code': {
    name: 'Claude Code',
    type: 'Development Tool',
    category: 'Terminal AI',
    description: 'Terminal-native development with Claude 3.7 Sonnet',
    pricing: '$20-$200/month',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': false,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false
    }
  }
};

export const featureCategories: Record<string, string[]> = {
  'Development Capabilities': [
    'Real-time code completion',
    'Multi-file editing',
    'Design-to-code conversion',
    'React component generation',
    'Vue.js support',
    'Angular support',
    'TypeScript support',
    'Tailwind CSS integration',
    'Native IDE integration',
    'Context Window Size',
    'SWE-bench Score',
    'Semantic/deep search'
  ],
  'Quality & Optimization': [
    'Responsive design generation',
    'Accessibility (WCAG) compliance',
    'Performance optimization suggestions',
    'Bundle size analysis',
    'SEO optimization',
    'Error debugging assistance',
    'Code refactoring',
    'Browser compatibility checks',
    'Advanced reasoning mode',
    'Autonomous agent mode'
  ],
  'Modern Web Features': [
    'Mobile-first design',
    'Dark mode support',
    'Internationalization (i18n)',
    'PWA features',
    'Offline capabilities',
    'Voice/audio input',
    'Image/design upload',
    'Video processing',
    'Multimodal capabilities',
    'Screenshot-to-code',
    '3D graphics support'
  ],
  'Workflow Integration': [
    'Git integration',
    'Live preview/hot reload',
    'Collaborative editing',
    'Custom component libraries',
    'API integration assistance',
    'Testing code generation',
    'Documentation generation',
    'Search',
    'Terminal integration'
  ],
  'Business & Deployment': [
    'Free tier available',
    'Open source',
    'Self-hosting option',
    'Enterprise features',
    'Privacy mode',
    'Custom model training',
    'API Cost (per 1M tokens)',
    'Context Window',
    'Monthly Pricing',
    'Enterprise Pricing'
  ]
};

// AI Model specific features
export const aiModelFeatures: Record<string, string[]> = {
  'AI Model Capabilities': [
    'Advanced reasoning mode',
    'Video processing',
    'Multimodal capabilities',
    'Context Window Size',
    'SWE-bench Score'
  ]
};

// Development Tool specific features
export const developmentToolFeatures: Record<string, string[]> = {
  'Tool Integration': [
    'Native IDE integration',
    'Terminal integration',
    'Autonomous agent mode'
  ],
  'Workflow Features': [
    'Git integration',
    'Live preview/hot reload',
    'Collaborative editing',
    'Custom component libraries',
    'API integration assistance',
    'Testing code generation',
    'Documentation generation',
    'Semantic/deep search'
  ]
};

// Helper functions
export function getAIModels(): Record<string, ToolData> {
  return Object.fromEntries(
    Object.entries(toolData).filter(([_, tool]) => tool.type === 'AI Model')
  );
}

export function getDevelopmentTools(): Record<string, ToolData> {
  return Object.fromEntries(
    Object.entries(toolData).filter(([_, tool]) => tool.type === 'Development Tool')
  );
}

export function getToolsByCategory(category: string): Record<string, ToolData> {
  return Object.fromEntries(
    Object.entries(toolData).filter(([_, tool]) => tool.category === category)
  );
}

export function getRelevantFeatureCategories(selectedTools: string[]): Record<string, string[]> {
  const hasAIModels = selectedTools.some(id => toolData[id]?.type === 'AI Model');
  const hasDevTools = selectedTools.some(id => toolData[id]?.type === 'Development Tool');
  
  let relevantCategories = { ...featureCategories };
  
  // Add AI-specific features if AI models are selected
  if (hasAIModels) {
    relevantCategories = { ...relevantCategories, ...aiModelFeatures };
  }
  
  // Add tool-specific features if development tools are selected
  if (hasDevTools) {
    relevantCategories = { ...relevantCategories, ...developmentToolFeatures };
  }
  
  return relevantCategories;
}