// src/lib/data.ts
export interface ToolData {
  name: string;
  type: 'AI Model' | 'Development Tool';
  category: string;
  description: string;
  features: Record<string, boolean | string>;
  pricing?: string;
  benchmark?: string;
}

export const toolData: Record<string, ToolData> = {
  // ============================================================================
  // AI MODELS SECTION
  // ============================================================================

  'claude-opus-45': {
    name: 'Claude Opus 4.5',
    type: 'AI Model',
    category: 'Premium AI',
    description: 'The performance benchmark with 1490 WebDev AI Elo. Best-in-class autonomous agent capabilities.',
    pricing: '$5/$25 per 1M tokens',
    benchmark: '1490 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '200K',
      'WebDev AI Leader Board': '1490',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': 'Limited',
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$5/$25',
      'Max Context Output': '64K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'claude-fable-5': {
    name: 'Claude Fable 5',
    type: 'AI Model',
    category: 'Frontier AI',
    description: 'The frontier breaker 🆕 — enters at #1 with 1653 Elo on WebDev Arena, 92 points clear of #2, the widest gap this table has ever recorded. Anthropic\'s first generally available Mythos-class model: 1M context, 128K output, always-on adaptive thinking. At $10/$50 it is the most expensive model in the table, with mandatory 30-day data retention.',
    pricing: '$10/$50 per 1M tokens',
    benchmark: '1653 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M',
      'WebDev AI Leader Board': '1653',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': '✅ (Always-on)',
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$10/$50',
      'Max Context Output': '128K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'claude-opus-48': {
    name: 'Claude Opus 4.8',
    type: 'AI Model',
    category: 'Premium AI',
    description: 'The agentic upgrade 🆕 — enters at #2 with 1561 Elo, replacing Opus 4.7 at unchanged $5/$25 pricing. Fewer compactions on long agentic runs, better tool triggering, fast mode at 2.5x output speed, and a lower prompt cache minimum (1,024 vs 2,048 tokens).',
    pricing: '$5/$25 per 1M tokens',
    benchmark: '1561 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M',
      'WebDev AI Leader Board': '1561',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$5/$25 (unchanged from Opus 4.7)',
      'Max Context Output': '128K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'claude-opus-46': {
    name: 'Claude Opus 4.6',
    type: 'AI Model',
    category: 'Premium AI',
    description: 'The proven performer — 1M context, 128K output, Agent Teams, adaptive thinking, and the deepest MCP ecosystem. Stable at 1536 Elo on WebDev Arena. Stable workflows have no urgency to migrate.',
    pricing: '$5/$25 (standard) / $10/$37.50 (>200K tokens)',
    benchmark: '1536 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M',
      'WebDev AI Leader Board': '1536',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': 'Limited',
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$5/$25 (standard) / $10/$37.50 (>200K tokens)',
      'Max Context Output': '128K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'claude-opus-47': {
    name: 'Claude Opus 4.7',
    type: 'AI Model',
    category: 'Premium AI',
    description: 'The proven performer ⬇️ — drops from #1 to #5, displaced by its own successor and Fable 5. At 1557 Elo it is only 4 points below Opus 4.8 on the same $5/$25 pricing, making the upgrade path obvious. Expect this to exit the top 5 next month as adoption shifts to 4.8.',
    pricing: '$5/$25 per 1M tokens',
    benchmark: '1557 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M',
      'WebDev AI Leader Board': '1557',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$5/$25 (unchanged from Opus 4.6)',
      'Max Context Output': '128K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'claude-sonnet-46': {
    name: 'Claude Sonnet 4.6',
    type: 'AI Model',
    category: 'General Purpose AI',
    description: 'The accessible powerhouse — holds at #5. Default free model on claude.ai with 1M context window (beta), adaptive thinking, and near-Opus performance at $3/$15 Sonnet pricing. Best value in the Claude lineup.',
    pricing: '$3/$15 per 1M tokens',
    benchmark: '1522 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M (beta)',
      'WebDev AI Leader Board': '1522',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$3/$15',
      'Max Context Output': '64K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'deepseek-v4-pro': {
    name: 'DeepSeek V4 Pro',
    type: 'AI Model',
    category: 'Open Source AI',
    description: 'The pricing earthquake — matches frontier performance at 34x cheaper. $0.435/$0.87 per 1M tokens with permanent pricing since May 22. Cache-hit input at $0.003625. Full quality profile of models costing 10-30x more.',
    pricing: '$0.435/$0.87 per 1M tokens',
    benchmark: '1446 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M',
      'WebDev AI Leader Board': '1446',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': false,
      'Image/design upload': 'Limited',
      'Video processing': false,
      'Multimodal capabilities': 'Limited',
      'Free tier available': true,
      'Open source': true,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$0.435/$0.87 (permanent since May 22 — cache-hit input $0.003625)',
      'Max Context Output': '16K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'gemini-3-pro': {
    name: 'Gemini 3 Pro',
    type: 'AI Model',
    category: 'Multimodal AI',
    description: 'Full video processing and 24-language voice support. Tiered pricing at $2/$12 (<200K tokens) and $4/$18 (>200K tokens).',
    pricing: '$2-4/$12-18 per 1M tokens',
    benchmark: '1439 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M',
      'WebDev AI Leader Board': '1439',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': true,
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': 'Limited',
      'API Cost (per 1M tokens)': '$2/$12 (<200k tokens)\n$4/$18 (>200k tokens)',
      'Max Context Output': '64K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'gemini-31-pro': {
    name: 'Gemini 3.1 Pro',
    type: 'AI Model',
    category: 'Multimodal AI',
    description: 'The efficiency champion with tiered thinking levels (Low/Medium/High). Full multimodal with 24-language voice, video processing, and native capabilities.',
    pricing: '$2-4/$12-18 per 1M tokens',
    benchmark: '1445 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M',
      'WebDev AI Leader Board': '1445',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': true,
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': 'Limited',
      'API Cost (per 1M tokens)': '$2/$12 (<200K) / $4/$18 (>200K)',
      'Max Context Output': '64K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'glm-46': {
    name: 'GLM-4.6',
    type: 'AI Model',
    category: 'Open Source AI',
    description: 'Open-source coding model with full multimodal capabilities including voice, image, and video processing.',
    pricing: '$0.35/$0.39 per 1M tokens',
    benchmark: '1355 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '200K',
      'WebDev AI Leader Board': '1355',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': 'Limited',
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': true,
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': true,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$0.35/$0.39',
      'Max Context Output': '128K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'glm-5': {
    name: 'GLM-5',
    type: 'AI Model',
    category: 'Open Source AI',
    description: 'The open-source leader with MIT license, self-hostable on vLLM/SGLang/Huawei Ascend. 744B MoE architecture (40B active per token). Strongest open-source value play at frontier performance.',
    pricing: '$1.00/$3.20 per 1M tokens',
    benchmark: '1430 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '200K',
      'WebDev AI Leader Board': '1430',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': true,
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': true,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$1.00/$3.20',
      'Max Context Output': '131K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'gpt-52': {
    name: 'GPT-5.2',
    type: 'AI Model',
    category: 'General Purpose AI',
    description: 'The balanced performer with solid reasoning and massive 400K context window.',
    pricing: '$1.75/$14 per 1M tokens',
    benchmark: '1405 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '400K',
      'WebDev AI Leader Board': '1405',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': true,
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$1.75/$14',
      'Max Context Output': '128K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'gpt-54': {
    name: 'GPT-5.4',
    type: 'AI Model',
    category: 'General Purpose AI',
    description: 'OpenAI\'s first model combining frontier coding, native computer use (75% OSWorld), and knowledge work. Introduces Tool Search cutting token usage by 47%.',
    pricing: '$2.50/$15 (Standard) / $30/$180 (Pro)',
    benchmark: '1457 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M',
      'WebDev AI Leader Board': '1457',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': true,
      'Multimodal capabilities': true,
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$2.50/$15 (Standard) / $30/$180 (Pro)',
      'Max Context Output': '128K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'gpt-55': {
    name: 'GPT-5.5',
    type: 'AI Model',
    category: 'General Purpose AI',
    description: 'The autonomous workhorse ⬇️ — drops two spots as Fable 5 and Opus 4.8 enter above it. Terminal-Bench 2.0 leader at 82.7% with 52.5% fewer hallucinations than GPT-5.4, but WebDev Arena sits at 1501 Elo, 152 points behind Fable 5. Still no public API pricing, limited to ChatGPT subscription tiers and Codex.',
    pricing: '$5/$10 (Standard)',
    benchmark: '1501 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M',
      'WebDev AI Leader Board': '1501',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': true,
      'Multimodal capabilities': true,
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$5/$10 (Standard)',
      'Max Context Output': '64K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'grok-43': {
    name: 'Grok 4.3',
    type: 'AI Model',
    category: 'Specialized Coding AI',
    description: 'Always-on reasoning with native tool use and full video input (mp4/mov/webm, 5 min at 1080p). One of only six models with full video processing.',
    pricing: '$1.25/$2.50 per 1M tokens',
    benchmark: '1363 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M',
      'WebDev AI Leader Board': '1363',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': '✅ (Always-on)',
      'Tool use capabilities': '✅ (Native)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': true,
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$1.25/$2.50',
      'Max Context Output': '30K',
      'Batch processing discount': false,
      'Prompt caching discount': false
    }
  },

  'kimi-k25': {
    name: 'Kimi K2.5',
    type: 'AI Model',
    category: 'Agentic AI',
    description: 'Open-source with full video processing, native multimodal capabilities, and Agent Swarm enabling up to 100 sub-agents.',
    pricing: '$0.60/$2.00 per 1M tokens',
    benchmark: '1431 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '256K',
      'WebDev AI Leader Board': '1431',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': 'Limited',
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': 'Limited',
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': true,
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': true,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$0.60/$2.00',
      'Max Context Output': '64K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'kimi-k26': {
    name: 'Kimi K2.6',
    type: 'AI Model',
    category: 'Agentic AI',
    description: 'Leaps to #8 on WebDev Arena with 300-agent swarms and 12-hour autonomous sessions. Open-weight with Modified MIT licensing, undercutting every closed frontier model.',
    pricing: '$0.95/$4.00 per 1M tokens',
    benchmark: '1514 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '262.1K',
      'WebDev AI Leader Board': '1514',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': 'Limited',
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': true,
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': true,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$0.95/$4.00',
      'Max Context Output': '65.5K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'llama-4-maverick': {
    name: 'Llama 4 Maverick',
    type: 'AI Model',
    category: 'Open Source AI',
    description: 'Meta\'s latest open-source model with native early fusion multimodal and 200-language support.',
    pricing: '$0.19-0.49 (estimated) per 1M tokens',
    benchmark: 'N/A',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '10M (Scout) / 256K (Maverick)',
      'WebDev AI Leader Board': '❌',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': '✅ (200 langs)',
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': 'Limited',
      'Image/design upload': '✅ (up to 8-10)',
      'Video processing': 'Limited',
      'Multimodal capabilities': '✅ (Native, Early Fusion)',
      'Free tier available': true,
      'Open source': '✅ (Apache 2.0)',
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$0.19-0.49 (estimated)',
      'Max Context Output': '256K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'qwen-37-max': {
    name: 'Qwen 3.7 Max',
    type: 'AI Model',
    category: 'Agentic AI',
    description: 'The agent-first dark horse ↔️ — holds its spot at #3 but its WebDev Arena score settled from 1541 to 1526, now below Opus 4.6. The value case at $2.50/$7.50 remains strong. Still text-only with zero vision input. Alibaba demo ran 35 hours autonomously with 1,158 tool calls.',
    pricing: '$2.50/$7.50 per 1M tokens',
    benchmark: '1526 Elo',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': false,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M',
      'WebDev AI Leader Board': '1526',
      'Semantic/deep search': 'Limited',
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': false,
      'Image/design upload': false,
      'Video processing': false,
      'Multimodal capabilities': false,
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': 'Limited',
      'API Cost (per 1M tokens)': '$2.50/$7.50 (cached input $0.25 — 90% discount)',
      'Max Context Output': '65.5K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  // ============================================================================
  // DEVELOPMENT TOOLS SECTION
  // ============================================================================

  'github-copilot': {
    name: 'GitHub Copilot',
    type: 'Development Tool',
    category: 'IDE Integration',
    description: 'AI pair programmer with ecosystem integration',
    pricing: 'Free-$39',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': false,
      'Autonomous agent mode': 'Limited',
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': true,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': 'Limited',
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': 'Limited',
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'Monthly Pricing': 'Free-$39',
      'Enterprise Pricing': '$39/user'
    }
  },

  'cursor-ide': {
    name: 'Cursor IDE',
    type: 'Development Tool',
    category: 'AI-Native IDE',
    description: 'Cursor – The agent-first powerhouse ↔️ — holds #2 on product quality but the story this month is ownership. SpaceX announced a $60 billion all-stock acquisition of Anysphere on June 16, expected to close Q3 2026. Cursor gains xAI\'s Colossus infrastructure for Composer model training. Best full-IDE: Composer 2, multi-repo workspaces, parallel local/cloud agents, plugin marketplace, commit-to-merged-PR.',
    pricing: 'Free-$200',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': '✅ (Full IDE)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': false,
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': true,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': false,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': 'Privacy mode',
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': 'Free-$200',
      'Enterprise Pricing': '$40/user'
    }
  },

  'windsurf': {
    name: 'Windsurf',
    type: 'Development Tool',
    category: 'AI-Native IDE',
    description: 'Windsurf – The agentic workflow champion ↔️ — holds at #4. Arena Mode, Plan Mode, parallel multi-agent sessions with Git worktrees, and Cascade agent remain excellent. Claude Opus 4.8 support now live. Best balance of features and price ($Free-$60) for developers wanting a full IDE without Cursor\'s premium tier or ownership questions.',
    pricing: 'Free-$60',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': '✅ (Full IDE)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': 'Limited',
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': false,
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': true,
      'Collaborative editing': true,
      'Custom component libraries': false,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': false,
      'PWA features': false,
      'Offline capabilities': false,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': 'Free-$60',
      'Enterprise Pricing': '$60/user'
    }
  },

  'vercel-v0': {
    name: 'Vercel v0',
    type: 'Development Tool',
    category: 'UI Generator',
    description: 'React/Next.js UI generation from text',
    pricing: '$5-$30/month',
    features: {
      'Real-time code completion': false,
      'Multi-file editing': false,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': false,
      'Angular support': false,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': false,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': false,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': false,
      'Autonomous agent mode': false,
      'Git integration': false,
      'Live preview/hot reload': true,
      'Collaborative editing': false,
      'Custom component libraries': true,
      'API integration assistance': false,
      'Testing code generation': false,
      'Documentation generation': false,
      'Search': false,
      'Semantic/deep search': false,
      'Terminal integration': false,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': false,
      'PWA features': false,
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': false,
      'Custom model training': false,
      'Monthly Pricing': '$5-$30',
      'Enterprise Pricing': 'Custom'
    }
  },

  'bolt-new': {
    name: 'Bolt.new',
    type: 'Development Tool',
    category: 'Full-Stack Builder',
    description: 'Full-stack web applications with WebContainers',
    pricing: 'Beta',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': false,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': false,
      'Performance optimization suggestions': false,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': false,
      'Autonomous agent mode': 'Limited',
      'Git integration': true,
      'Live preview/hot reload': true,
      'Collaborative editing': false,
      'Custom component libraries': false,
      'API integration assistance': true,
      'Testing code generation': false,
      'Documentation generation': false,
      'Search': false,
      'Semantic/deep search': false,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': false,
      'PWA features': false,
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': 'Partial',
      'Self-hosting option': true,
      'Enterprise features': false,
      'Privacy mode': false,
      'Custom model training': false,
      'Monthly Pricing': 'Beta',
      'Enterprise Pricing': 'Custom'
    }
  },

  'lovable-ai': {
    name: 'Lovable AI',
    type: 'Development Tool',
    category: 'Full-Stack Builder',
    description: 'AI-powered full-stack app development',
    pricing: 'Free-$30/month',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': false,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': 'Limited',
      'Performance optimization suggestions': 'Limited',
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': 'Limited',
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': true,
      'Collaborative editing': true,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': false,
      'Documentation generation': true,
      'Search': false,
      'Semantic/deep search': false,
      'Terminal integration': false,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': 'Limited',
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': 'Limited',
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': 'Free-$30',
      'Enterprise Pricing': 'Custom'
    }
  },

  'claude-code': {
    name: 'Claude Code',
    type: 'Development Tool',
    category: 'Terminal AI',
    description: 'The quality-first professional tool ↔️ — holds #3 but is meaningfully stronger. Now runs Fable 5 (1653 Elo, the highest WebDev Arena score of any model in any tool) and Opus 4.8, and computer use (launched March 2026) lets it open apps, navigate browsers, and interact with dev tools directly from the terminal. Blind reviews show output preferred 67% vs Codex 25%.',
    pricing: '$20-$200/month',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': '✅ (CLI)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': 'Limited',
      'Collaborative editing': false,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Computer use': true,
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': '$20-$200',
      'Enterprise Pricing': 'Custom'
    }
  },

  'codex': {
    name: 'Codex AI',
    type: 'Development Tool',
    category: 'Terminal AI',
    description: 'AI-powered command line development tool. Now runs GPT-5.4 as its default model.',
    pricing: '$20-$200/month',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': '✅ (CLI)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': 'Limited',
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': false,
      'Custom component libraries': 'Limited',
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': 'Limited',
      'PWA features': 'Limited',
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': 'Limited',
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': '$20-$200',
      'Enterprise Pricing': 'Custom'
    }
  },

  'kimi-code': {
    name: 'Kimi Code',
    type: 'Development Tool',
    category: 'Command Line AI',
    description: 'Open-source agentic coding companion to Kimi K2.5 with IDE integration for VSCode, Cursor, and Zed. Supports images and videos for visual debugging.',
    pricing: 'Free-$0.15/month',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': 'Limited',
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': 'Limited',
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': 'Limited',
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': false,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': 'Limited',
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': true,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'Monthly Pricing': 'Free-$0.15',
      'Enterprise Pricing': 'Custom'
    }
  },

  'kiru': {
    name: 'Kiru',
    type: 'Development Tool',
    category: 'Spec-Driven IDE',
    description: 'The first spec-driven AI IDE: natural language prompts become structured EARS notation requirements, architecture designs, and sequenced implementation tasks. Agent hooks auto-generate tests and docs on file save. CLI 2.0 adds Windows and headless CI/CD support.',
    pricing: 'Free-$200',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': false,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': 'Limited',
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': 'Free-$200',
      'Enterprise Pricing': 'Custom (GovCloud ~20% higher)'
    }
  },

  'antigravity': {
    name: 'AntiGravity',
    type: 'Development Tool',
    category: 'AI-Native IDE',
    description: 'Antigravity – The free disruptor ↔️ — holds at #5 and retains its core advantage: completely free during preview. Multi-agent orchestration, integrated Chrome browser automation, and the most diverse free model lineup keep it the best zero-cost option. Built in Go with async workflows and fast agent execution.',
    pricing: 'Free / $19.99 (Google AI Pro)',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': '✅ (Full IDE)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': true,
      'Collaborative editing': false,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': 'Free / $19.99 (Google AI Pro)',
      'Enterprise Pricing': 'Incoming'
    }
  },

  'opencode': {
    name: 'OpenCode',
    type: 'Development Tool',
    category: 'Open Source CLI',
    description: 'The open infrastructure leader ↔️ — #1 tool with 160K+ GitHub stars and 7.5M monthly active developers. Model-agnostic access to 75+ providers (Claude, GPT, Gemini, DeepSeek, local via Ollama), unique LSP integration feeding compiler diagnostics to the model, background subagents, Scout agent for external research, and true air-gapped deployment. MIT-licensed, fully forkable.',
    pricing: 'Free (BYOK) / $10 (Go) / Pay-as-you-go (Zen) / $200 (Black)',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': false,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': 'Limited',
      'Offline capabilities': true,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': true,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': 'Free (BYOK) / $10 (Go) / Pay-as-you-go (Zen) / $200 (Black — sold out)',
      'Enterprise Pricing': 'Custom'
    }
  }
};

// AI Model Categories
export const aiModelCategories: Record<string, string[]> = {
  'Development capabilities and framework support': [
    'Real-time code completion',
    'Multi-file editing',
    'Design-to-code conversion',
    'React component generation',
    'Vue.js support',
    'Angular support',
    'TypeScript support',
    'Tailwind CSS integration',
    'Total Context Window',
    'WebDev AI Leader Board',
    'Semantic/deep search',
    'Autonomous agent mode',
    'Extended thinking/reasoning',
    'Tool use capabilities'
  ],
  'Quality and optimization features': [
    'Responsive design generation',
    'Accessibility (WCAG) compliance',
    'Performance optimization suggestions',
    'Bundle size analysis',
    'SEO optimization',
    'Error debugging assistance',
    'Code refactoring',
    'Browser compatibility checks',
    'Advanced reasoning mode',
    'Code review capabilities',
    'Security/vulnerability detection',
    'Code quality scoring',
    'Architecture/design guidance',
    'Test generation',
    'Code style adherence'
  ],
  'Modern web development features': [
    'Mobile-first design',
    'Dark mode support',
    'Internationalization (i18n)',
    'PWA features',
    'Offline capabilities',
    'Voice/audio input',
    'Image/design upload',
    'Video processing',
    'Multimodal capabilities'
  ],
  'Business and deployment considerations': [
    'Free tier available',
    'Open source',
    'Self-hosting option',
    'Enterprise features',
    'Privacy mode',
    'Custom model training',
    'API Cost (per 1M tokens)',
    'Max Context Output',
    'Batch processing discount',
    'Prompt caching discount'
  ]
};

// Development Tool Categories
export const developmentToolCategories: Record<string, string[]> = {
  'Development Capabilities and Framework Support (Tools)': [
    'Real-time code completion',
    'Multi-file editing',
    'Design-to-code conversion',
    'React component generation',
    'Vue.js support',
    'Angular support',
    'TypeScript support',
    'Tailwind CSS integration',
    'Native IDE integration'
  ],
  'Quality and Optimization Features (Tools)': [
    'Responsive design generation',
    'Accessibility (WCAG) compliance',
    'Performance optimization suggestions',
    'Bundle size analysis',
    'SEO optimization',
    'Error debugging assistance',
    'Code refactoring',
    'Browser compatibility checks',
    'Autonomous agent mode'
  ],
  'Modern Web Development Features (Tools)': [
    'Mobile-first design',
    'Dark mode support',
    'Internationalization (i18n)',
    'PWA features',
    'Offline capabilities',
    'Voice/audio input',
    'Image/design upload',
    'Screenshot-to-code',
    '3D graphics support'
  ],
  'Development workflow integration': [
    'Git integration',
    'Live preview/hot reload',
    'Collaborative editing',
    'Custom component libraries',
    'API integration assistance',
    'Testing code generation',
    'Documentation generation',
    'Search',
    'Semantic/deep search',
    'Terminal integration',
    'Computer use'
  ],
  'Business and Deployment Considerations (Tools)': [
    'Free tier available',
    'Open source',
    'Self-hosting option',
    'Enterprise features',
    'Privacy mode',
    'Custom model training',
    'Monthly Pricing',
    'Enterprise Pricing'
  ]
};

// Helper functions
export function getAIModels(): Record<string, ToolData> {
  return Object.fromEntries(
    Object.entries(toolData).filter(([_, tool]) => tool.type === 'AI Model')
  );
}

export function getDevelopmentTools(): Record<string, ToolData> {
  return Object.fromEntries(
    Object.entries(toolData).filter(([_, tool]) => tool.type === 'Development Tool')
  );
}

export function getToolsByCategory(category: string): Record<string, ToolData> {
  return Object.fromEntries(
    Object.entries(toolData).filter(([_, tool]) => tool.category === category)
  );
}

export function getRelevantFeatureCategories(selectedTools: string[]): Record<string, string[]> {
  const hasAIModels = selectedTools.some(id => toolData[id]?.type === 'AI Model');
  const hasDevTools = selectedTools.some(id => toolData[id]?.type === 'Development Tool');

  if (hasAIModels && hasDevTools) {
    return { ...aiModelCategories, ...developmentToolCategories };
  } else if (hasAIModels) {
    return aiModelCategories;
  } else if (hasDevTools) {
    return developmentToolCategories;
  }

  return aiModelCategories;
}
