// src/lib/data.ts
export interface ToolData {
  name: string;
  type: 'AI Model' | 'Development Tool';
  category: string;
  description: string;
  features: Record<string, boolean | string>;
  pricing?: string;
  benchmark?: string;
}

export const toolData: Record<string, ToolData> = {
  // ============================================================================
  // AI MODELS SECTION
  // ============================================================================
  
  'claude-sonnet-4': {
    name: 'Claude 4 Sonnet',
    type: 'AI Model',
    category: 'General Purpose AI',
    description: 'Smart, efficient model for everyday coding tasks',
    pricing: '$3/$15 per 1M tokens',
    benchmark: '64.93% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': 'Limited',
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '200K',
      'SWE-bench Score': '64.93%',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': '✅ (Hybrid)',
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$3/$15',
      'Max Context Output': '64K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'claude-opus-4': {
    name: 'Claude 4 Opus',
    type: 'AI Model',
    category: 'Premium AI',
    description: 'Most capable model for complex development tasks',
    pricing: '$15/$75 per 1M tokens',
    benchmark: '67.6% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '200K',
      'SWE-bench Score': '67.6%',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': '✅ (Hybrid)',
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$15/$75',
      'Max Context Output': '32K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'claude-sonnet-45': {
    name: 'Claude Sonnet 4.5',
    type: 'AI Model',
    category: 'General Purpose AI',
    description: 'Latest Sonnet model with enhanced capabilities',
    pricing: '$3/$15 per 1M tokens',
    benchmark: '70% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '200K',
      'SWE-bench Score': '70%',
      'Semantic/deep search': true,
      'Autonomous agent mode': '✅ (Best-in-class)',
      'Extended thinking/reasoning': '✅ (Hybrid)',
      'Tool use capabilities': '✅ (Enhanced)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$3/$15',
      'Max Context Output': '64K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'claude-opus-41': {
    name: 'Claude Opus 4.1',
    type: 'AI Model',
    category: 'Premium AI',
    description: 'Latest Opus model with advanced features',
    pricing: '$15/$75 per 1M tokens',
    benchmark: '39.80% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '200K',
      'SWE-bench Score': '39.80%',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': '✅ (Hybrid)',
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': '✅ (Vision)',
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$15/$75',
      'Max Context Output': '32K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'glm-45': {
    name: 'GLM-4.5',
    type: 'AI Model',
    category: 'Open Source AI',
    description: 'Open-source MoE model with exceptional tool-use and bilingual capabilities',
    pricing: '$0.35/$0.39 per 1M tokens',
    benchmark: '54.20% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '128K',
      'SWE-bench Score': '54.20%',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': '✅ (Hybrid)',
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': '✅ (24+ languages, exceptional English-Chinese bilingual)',
      'PWA features': true,
      'Offline capabilities': 'Limited',
      'Voice/audio input': 'Limited',
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': '✅ (Vision)',
      'Free tier available': '✅ (Via Z.ai platform)',
      'Open source': '✅ (MIT License)',
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$0.35/$0.39',
      'Max Context Output': '131K',
      'Batch processing discount': true,
      'Prompt caching discount': '⚠️ (Not specified)'
    }
  },

  'gpt-41': {
    name: 'GPT-4.1',
    type: 'AI Model',
    category: 'General Purpose AI',
    description: 'Advanced language model with large context window',
    pricing: '$2/$8 per 1M tokens',
    benchmark: 'N/A',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M',
      'SWE-bench Score': false,
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$2/$8',
      'Max Context Output': '32.7K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'gemini-25-pro': {
    name: 'Gemini 2.5 Pro',
    type: 'AI Model',
    category: 'Multimodal AI',
    description: 'Multimodal AI with voice and visual capabilities',
    pricing: '$1.25/$10 per 1M tokens',
    benchmark: '53.60% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M',
      'SWE-bench Score': '53.60%',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': 'Limited',
      'Voice/audio input': '✅ (24 langs)',
      'Image/design upload': true,
      'Video processing': '✅ (Full)',
      'Multimodal capabilities': '✅ (Native)',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': 'Limited',
      'API Cost (per 1M tokens)': '$1.25/$10',
      'Max Context Output': '65K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'kimi-k2': {
    name: 'Kimi K2',
    type: 'AI Model',
    category: 'Agentic AI',
    description: 'Open agentic intelligence with massive parameter count',
    pricing: '$0.15/$2.50 per 1M tokens',
    benchmark: '43.80% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '128K',
      'SWE-bench Score': '43.80%',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': 'Limited',
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': 'Limited',
      'Voice/audio input': 'Limited',
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': 'Partial',
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$0.15/$2.50',
      'Max Context Output': '131.1K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'grok-4': {
    name: 'Grok 4',
    type: 'AI Model',
    category: 'Specialized Coding AI',
    description: 'First-principles reasoning with coding specialization',
    pricing: '$3/$15 per 1M tokens',
    benchmark: 'N/A',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '256K',
      'SWE-bench Score': false,
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': '✅ (Always-on)',
      'Tool use capabilities': '✅ (Native)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': '✅ (Always-on)',
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': '✅ (Limited)',
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$3/$15',
      'Max Context Output': '256K',
      'Batch processing discount': false,
      'Prompt caching discount': false
    }
  },

  'grok-4-fast': {
    name: 'Grok 4 Fast',
    type: 'AI Model',
    category: 'Specialized Coding AI',
    description: 'High-speed version of Grok 4',
    pricing: '$0.20-0.40/$0.50-1.00 per 1M tokens',
    benchmark: 'N/A',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '2M',
      'SWE-bench Score': false,
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': '✅ (Unified)',
      'Tool use capabilities': '✅ (RL-trained)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': '✅ (Limited)',
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$0.20-0.40/$0.50-1.00',
      'Max Context Output': '2M',
      'Batch processing discount': false,
      'Prompt caching discount': true
    }
  },

  'qwen-3-coder': {
    name: 'Qwen 3 Coder',
    type: 'AI Model',
    category: 'Open Source AI',
    description: 'Agentic coding model with repository-scale understanding',
    pricing: '$0.07-1.10 per 1M tokens',
    benchmark: '55.40% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '256K-1M',
      'SWE-bench Score': '55.40%',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': 'Limited',
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': 'Limited',
      'Free tier available': true,
      'Open source': true,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$0.07-1.10',
      'Max Context Output': '262K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'deepseek-coder': {
    name: 'DeepSeek Coder',
    type: 'AI Model',
    category: 'Open Source AI',
    description: 'High-performance open-source coding model',
    pricing: '$0.07-1.10 per 1M tokens',
    benchmark: '74.2% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': 'Limited',
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '128K',
      'SWE-bench Score': '74.2%',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': 'Limited',
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': 'Limited',
      'Free tier available': true,
      'Open source': true,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$0.07-1.10',
      'Max Context Output': '8.2K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  'gpt-5-medium': {
    name: 'GPT-5 (medium reasoning)',
    type: 'AI Model',
    category: 'General Purpose AI',
    description: 'High-performance model with advanced reasoning capabilities',
    pricing: '$1.25/$10 per 1M tokens',
    benchmark: '65% SWE-bench',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '400K',
      'SWE-bench Score': '65%',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Video processing': 'Limited',
      'Multimodal capabilities': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$1.25/$10',
      'Max Context Output': '128K',
      'Batch processing discount': '✅ (50%)',
      'Prompt caching discount': '✅ (90%)'
    }
  },

  'gemini-3-pro': {
    name: 'Gemini 3 Pro',
    type: 'AI Model',
    category: 'Multimodal AI',
    description: 'The new performance leader with groundbreaking SWE-bench score and unique full video processing capability.',
    pricing: '$2-4/$12-18 per 1M tokens',
    benchmark: '76.2% SWE-bench Verified',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '1M',
      'SWE-bench Score': '76.2%',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': '✅ (Enhanced)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': 'Limited',
      'Voice/audio input': '✅ (24 langs)',
      'Image/design upload': true,
      'Video processing': '✅ (Full)',
      'Multimodal capabilities': '✅ (Vision)',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'API Cost (per 1M tokens)': '$2/$12 (<200k tokens)\n$4/$18 (>200k tokens)',
      'Max Context Output': '64K',
      'Batch processing discount': false,
      'Prompt caching discount': false
    }
  },

  'llama-4-maverick': {
    name: 'Llama 4 Maverick',
    type: 'AI Model',
    category: 'Open Source AI',
    description: 'Meta\'s latest open-source model',
    pricing: '$0.19-0.49 (estimated) per 1M tokens',
    benchmark: 'N/A',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Total Context Window': '10M (Scout) / 256K (Maverick)',
      'SWE-bench Score': '54.20%',
      'Semantic/deep search': true,
      'Autonomous agent mode': true,
      'Extended thinking/reasoning': true,
      'Tool use capabilities': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': true,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Advanced reasoning mode': true,
      'Code review capabilities': true,
      'Security/vulnerability detection': true,
      'Code quality scoring': true,
      'Architecture/design guidance': true,
      'Test generation': true,
      'Code style adherence': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': '✅ (200 langs)',
      'PWA features': true,
      'Offline capabilities': true,
      'Voice/audio input': 'Limited',
      'Image/design upload': '✅ (up to 8-10)',
      'Video processing': 'Limited',
      'Multimodal capabilities': '✅ (Native, Early Fusion)',
      'Free tier available': true,
      'Open source': '✅ (Apache 2.0)',
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'API Cost (per 1M tokens)': '$0.19-0.49 (estimated)',
      'Max Context Output': '256K',
      'Batch processing discount': true,
      'Prompt caching discount': true
    }
  },

  // ============================================================================
  // DEVELOPMENT TOOLS SECTION
  // ============================================================================

  'github-copilot': {
    name: 'GitHub Copilot',
    type: 'Development Tool',
    category: 'IDE Integration',
    description: 'AI pair programmer with ecosystem integration',
    pricing: 'Free-$39',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': true,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': 'Limited',
      'Performance optimization suggestions': 'Limited',
      'Bundle size analysis': false,
      'SEO optimization': 'Limited',
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': 'Limited',
      'Autonomous agent mode': 'Limited',
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': true,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': 'Limited',
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': 'Limited',
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'Monthly Pricing': 'Free-$39',
      'Enterprise Pricing': '$39/user'
    }
  },

  'cursor-ide': {
    name: 'Cursor IDE',
    type: 'Development Tool',
    category: 'AI-Native IDE',
    description: 'AI-first code editor with autonomous capabilities',
    pricing: 'Free-$200',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': '✅ (Full IDE)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': 'Limited',
      'Performance optimization suggestions': 'Limited',
      'Bundle size analysis': false,
      'SEO optimization': 'Limited',
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': 'Limited',
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': false,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': false,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': 'Privacy mode',
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': 'Free-$200',
      'Enterprise Pricing': '$40/user'
    }
  },

  'windsurf': {
    name: 'Windsurf',
    type: 'Development Tool',
    category: 'AI-Native IDE',
    description: 'AI-powered editing with Cascade agent',
    pricing: 'Free-$60',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': '✅ (Full IDE)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': 'Limited',
      'Performance optimization suggestions': 'Limited',
      'Bundle size analysis': false,
      'SEO optimization': 'Limited',
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': 'Limited',
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': true,
      'Collaborative editing': true,
      'Custom component libraries': false,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': false,
      'PWA features': false,
      'Offline capabilities': false,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': 'Free-$60',
      'Enterprise Pricing': '$60/user'
    }
  },

  'vercel-v0': {
    name: 'Vercel v0',
    type: 'Development Tool',
    category: 'UI Generator',
    description: 'React/Next.js UI generation from text',
    pricing: '$5-$30/month',
    features: {
      'Real-time code completion': false,
      'Multi-file editing': false,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': false,
      'Angular support': false,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': false,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': 'Limited',
      'Performance optimization suggestions': 'Limited',
      'Bundle size analysis': false,
      'SEO optimization': 'Limited',
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': 'Limited',
      'Autonomous agent mode': false,
      'Git integration': false,
      'Live preview/hot reload': true,
      'Collaborative editing': false,
      'Custom component libraries': true,
      'API integration assistance': false,
      'Testing code generation': false,
      'Documentation generation': false,
      'Search': false,
      'Semantic/deep search': false,
      'Terminal integration': false,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': false,
      'PWA features': false,
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': false,
      'Custom model training': false,
      'Monthly Pricing': '$5-$30',
      'Enterprise Pricing': 'Custom'
    }
  },

  'bolt-new': {
    name: 'Bolt.new',
    type: 'Development Tool',
    category: 'Full-Stack Builder',
    description: 'Full-stack web applications with WebContainers',
    pricing: 'Beta',
    features: {
      'Real-time code completion': 'Limited',
      'Multi-file editing': 'Limited',
      'Design-to-code conversion': 'Limited',
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': false,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': 'Limited',
      'Performance optimization suggestions': 'Limited',
      'Bundle size analysis': false,
      'SEO optimization': 'Limited',
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': 'Limited',
      'Autonomous agent mode': 'Limited',
      'Git integration': true,
      'Live preview/hot reload': true,
      'Collaborative editing': false,
      'Custom component libraries': false,
      'API integration assistance': true,
      'Testing code generation': false,
      'Documentation generation': false,
      'Search': false,
      'Semantic/deep search': false,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': 'Limited',
      'Internationalization (i18n)': 'Limited',
      'PWA features': 'Limited',
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': 'Limited',
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': 'Partial',
      'Self-hosting option': true,
      'Enterprise features': false,
      'Privacy mode': false,
      'Custom model training': false,
      'Monthly Pricing': 'Beta',
      'Enterprise Pricing': 'Custom'
    }
  },

  'jetbrains-ai': {
    name: 'JetBrains AI',
    type: 'Development Tool',
    category: 'IDE Integration',
    description: 'AI assistant integrated into JetBrains IDEs',
    pricing: 'Free-Custom',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': '✅ (Full IDE)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': 'Limited',
      'Performance optimization suggestions': 'Limited',
      'Bundle size analysis': false,
      'SEO optimization': 'Limited',
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': 'Limited',
      'Autonomous agent mode': 'Limited',
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': false,
      'Custom component libraries': false,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': 'Limited',
      'Internationalization (i18n)': 'Limited',
      'PWA features': 'Limited',
      'Offline capabilities': true,
      'Voice/audio input': false,
      'Image/design upload': 'Limited',
      'Screenshot-to-code': 'Limited',
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': 'Free-Custom',
      'Enterprise Pricing': 'Custom'
    }
  },

  'lovable-ai': {
    name: 'Lovable AI',
    type: 'Development Tool',
    category: 'Full-Stack Builder',
    description: 'AI-powered full-stack app development',
    pricing: 'Free-$30/month',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': false,
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': 'Limited',
      'Performance optimization suggestions': 'Limited',
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': 'Limited',
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': true,
      'Collaborative editing': true,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': false,
      'Documentation generation': true,
      'Search': false,
      'Semantic/deep search': false,
      'Terminal integration': false,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': 'Limited',
      'PWA features': 'Limited',
      'Offline capabilities': true,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': 'Limited',
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': 'Limited',
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': 'Free-$30',
      'Enterprise Pricing': 'Custom'
    }
  },

  'gemini-cli': {
    name: 'Gemini CLI',
    type: 'Development Tool',
    category: 'Command Line AI',
    description: 'Open-source AI agent for terminal workflows',
    pricing: 'Free',
    features: {
      'Real-time code completion': 'Limited',
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': '✅ (CLI)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': false,
      'Custom component libraries': 'Limited',
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': 'Limited',
      'Terminal integration': 'Limited',
      'Mobile-first design': true,
      'Dark mode support': 'Limited',
      'Internationalization (i18n)': 'Limited',
      'PWA features': 'Limited',
      'Offline capabilities': false,
      'Voice/audio input': true,
      'Image/design upload': true,
      'Screenshot-to-code': 'Limited',
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': true,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': 'Free',
      'Enterprise Pricing': 'Custom'
    }
  },

  'claude-code': {
    name: 'Claude Code',
    type: 'Development Tool',
    category: 'Terminal AI',
    description: 'Terminal-native development with Claude',
    pricing: '$20-$200/month',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': '✅ (CLI)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': false,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': 'Limited',
      'Internationalization (i18n)': 'Limited',
      'PWA features': 'Limited',
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': 'Limited',
      '3D graphics support': 'Limited',
      'Free tier available': false,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': '$20-$200',
      'Enterprise Pricing': 'Custom'
    }
  },

  'codex': {
    name: 'Codex',
    type: 'Development Tool',
    category: 'Terminal AI',
    description: 'AI-powered command line development tool',
    pricing: '$20-$200/month',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': '✅ (CLI)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': 'Limited',
      'Performance optimization suggestions': 'Limited',
      'Bundle size analysis': false,
      'SEO optimization': 'Limited',
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': 'Limited',
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': false,
      'Custom component libraries': 'Limited',
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': 'Limited',
      'Internationalization (i18n)': 'Limited',
      'PWA features': 'Limited',
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': false,
      'Screenshot-to-code': false,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': '$20-$200',
      'Enterprise Pricing': 'Custom'
    }
  },

  'antigravity': {
    name: 'AntiGravity',
    type: 'Development Tool',
    category: 'AI-Native IDE',
    description: 'The free disruptor with multi-agent orchestration and integrated Chrome browser automation.',
    pricing: 'Free',
    features: {
      'Real-time code completion': true,
      'Multi-file editing': true,
      'Design-to-code conversion': true,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': '✅ (Full IDE)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': true,
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': true,
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': true,
      'Autonomous agent mode': '✅ (Multi-agent orchestration)',
      'Git integration': true,
      'Live preview/hot reload': true,
      'Collaborative editing': false,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': true,
      'Mobile-first design': true,
      'Dark mode support': true,
      'Internationalization (i18n)': true,
      'PWA features': true,
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': true,
      'Screenshot-to-code': true,
      '3D graphics support': true,
      'Free tier available': true,
      'Open source': false,
      'Self-hosting option': false,
      'Enterprise features': '✅ (Coming soon)',
      'Privacy mode': true,
      'Custom model training': false,
      'Monthly Pricing': 'Free',
      'Enterprise Pricing': 'TBD'
    }
  },

  'kimi-k2-cli': {
    name: 'Kimi K2 CLI',
    type: 'Development Tool',
    category: 'Command Line AI',
    description: 'Open-source terminal AI with agentic coding and multi-file refactoring',
    pricing: 'Free-$0.15/month',
    features: {
      'Real-time code completion': 'Limited',
      'Multi-file editing': true,
      'Design-to-code conversion': false,
      'React component generation': true,
      'Vue.js support': true,
      'Angular support': true,
      'TypeScript support': true,
      'Tailwind CSS integration': true,
      'Native IDE integration': '✅ (CLI)',
      'Responsive design generation': true,
      'Accessibility (WCAG) compliance': 'Limited',
      'Performance optimization suggestions': true,
      'Bundle size analysis': false,
      'SEO optimization': 'Limited',
      'Error debugging assistance': true,
      'Code refactoring': true,
      'Browser compatibility checks': 'Limited',
      'Autonomous agent mode': true,
      'Git integration': true,
      'Live preview/hot reload': false,
      'Collaborative editing': false,
      'Custom component libraries': true,
      'API integration assistance': true,
      'Testing code generation': true,
      'Documentation generation': true,
      'Search': true,
      'Semantic/deep search': true,
      'Terminal integration': '✅ (Native)',
      'Mobile-first design': true,
      'Dark mode support': 'Limited',
      'Internationalization (i18n)': 'Limited',
      'PWA features': 'Limited',
      'Offline capabilities': false,
      'Voice/audio input': false,
      'Image/design upload': false,
      'Screenshot-to-code': false,
      '3D graphics support': 'Limited',
      'Free tier available': true,
      'Open source': true,
      'Self-hosting option': true,
      'Enterprise features': true,
      'Privacy mode': true,
      'Custom model training': true,
      'Monthly Pricing': 'Free-$0.15',
      'Enterprise Pricing': 'Custom'
    }
  }
};

// AI Model Categories
export const aiModelCategories: Record<string, string[]> = {
  'Development capabilities and framework support': [
    'Real-time code completion',
    'Multi-file editing',
    'Design-to-code conversion',
    'React component generation',
    'Vue.js support',
    'Angular support',
    'TypeScript support',
    'Tailwind CSS integration',
    'Total Context Window',
    'SWE-bench Score',
    'Semantic/deep search',
    'Autonomous agent mode',
    'Extended thinking/reasoning',
    'Tool use capabilities'
  ],
  'Quality and optimization features': [
    'Responsive design generation',
    'Accessibility (WCAG) compliance',
    'Performance optimization suggestions',
    'Bundle size analysis',
    'SEO optimization',
    'Error debugging assistance',
    'Code refactoring',
    'Browser compatibility checks',
    'Advanced reasoning mode',
    'Code review capabilities',
    'Security/vulnerability detection',
    'Code quality scoring',
    'Architecture/design guidance',
    'Test generation',
    'Code style adherence'
  ],
  'Modern web development features': [
    'Mobile-first design',
    'Dark mode support',
    'Internationalization (i18n)',
    'PWA features',
    'Offline capabilities',
    'Voice/audio input',
    'Image/design upload',
    'Video processing',
    'Multimodal capabilities'
  ],
  'Business and deployment considerations': [
    'Free tier available',
    'Open source',
    'Self-hosting option',
    'Enterprise features',
    'Privacy mode',
    'Custom model training',
    'API Cost (per 1M tokens)',
    'Max Context Output',
    'Batch processing discount',
    'Prompt caching discount'
  ]
};

// Development Tool Categories  
export const developmentToolCategories: Record<string, string[]> = {
  'Development Capabilities and Framework Support (Tools)': [
    'Real-time code completion',
    'Multi-file editing',
    'Design-to-code conversion',
    'React component generation',
    'Vue.js support',
    'Angular support',
    'TypeScript support',
    'Tailwind CSS integration',
    'Native IDE integration'
  ],
  'Quality and Optimization Features (Tools)': [
    'Responsive design generation',
    'Accessibility (WCAG) compliance',
    'Performance optimization suggestions',
    'Bundle size analysis',
    'SEO optimization',
    'Error debugging assistance',
    'Code refactoring',
    'Browser compatibility checks',
    'Autonomous agent mode'
  ],
  'Modern Web Development Features (Tools)': [
    'Mobile-first design',
    'Dark mode support',
    'Internationalization (i18n)',
    'PWA features',
    'Offline capabilities',
    'Voice/audio input',
    'Image/design upload',
    'Screenshot-to-code',
    '3D graphics support'
  ],
  'Development workflow integration': [
    'Git integration',
    'Live preview/hot reload',
    'Collaborative editing',
    'Custom component libraries',
    'API integration assistance',
    'Testing code generation',
    'Documentation generation',
    'Search',
    'Semantic/deep search',
    'Terminal integration'
  ],
  'Business and Deployment Considerations (Tools)': [
    'Free tier available',
    'Open source',
    'Self-hosting option',
    'Enterprise features',
    'Privacy mode',
    'Custom model training',
    'Monthly Pricing',
    'Enterprise Pricing'
  ]
};

// Helper functions
export function getAIModels(): Record<string, ToolData> {
  return Object.fromEntries(
    Object.entries(toolData).filter(([_, tool]) => tool.type === 'AI Model')
  );
}

export function getDevelopmentTools(): Record<string, ToolData> {
  return Object.fromEntries(
    Object.entries(toolData).filter(([_, tool]) => tool.type === 'Development Tool')
  );
}
 
export function getToolsByCategory(category: string): Record<string, ToolData> {
  return Object.fromEntries(
    Object.entries(toolData).filter(([_, tool]) => tool.category === category)
  );
}

export function getRelevantFeatureCategories(selectedTools: string[]): Record<string, string[]> {
  const hasAIModels = selectedTools.some(id => toolData[id]?.type === 'AI Model');
  const hasDevTools = selectedTools.some(id => toolData[id]?.type === 'Development Tool');
  
  if (hasAIModels && hasDevTools) {
    return { ...aiModelCategories, ...developmentToolCategories };
  } else if (hasAIModels) {
    return aiModelCategories;
  } else if (hasDevTools) {
    return developmentToolCategories;
  }
  
  return aiModelCategories;
}